sources:
  - name: uniswapv3
    handler:
      graphql:
        endpoint: https://gateway.thegraph.com/api/eada99c8eee80663db1e909b89c14a3f/subgraphs/id/5zvR82QoaXYFyDEKLZ9t6v9adgnptxYpKpSbxtgVENFV
plugins:
  - pollingLive:
      defaultInterval: 2000
documents:
  - operations.gql