fragment PoolLiveDataFields on Pool {
  liquidity
  tick
  sqrtPrice
  feeTier
  id
}

query GetMultipleArbitrumPoolLiveData($poolIds: [ID!]!) @live(interval: 5000) {
  uniswapv3_arbitrum: pools(where: { id_in: $poolIds }) {
    ...PoolLiveDataFields
  }
}
