DELIMITER //
DROP procedure IF EXISTS `SP_LOCK_PENDING_PAYMENTS`;//

CREATE PROCEDURE `SP_LOCK_PENDING_PAYMENTS`(
    IN IN_PAYMENT_ID BIGINT)
BEGIN

START TRANSACTION READ WRITE;

SELECT p.*
FROM PAYMENT p
WHERE p.PAYMENT_ID = IN_PAYMENT_ID AND p.STATUS = 'pending' FOR UPDATE;

END;
//

DELIMITER ;