const hre = require("hardhat");

async function main() {
  console.log("deploying...");
  // const provider = new ethers.JsonRpcProvider('https://virtual.mainnet.rpc.tenderly.co/7cf36273-4f0d-4712-a3ed-7a2601108ebb')
  // const privateKey = '0xe21a8a3f8c5b7169ea3fe3c732a3eef519d43e4a6e55095a1d1bb0ef99896623'
  // const wallet = new hre.ethers.Wallet(privateKey, provider)
  // console.log('wallet address: ', wallet.address)
 
  // const BookLibrary = (await hre.ethers.getContractFactory("BookLibrary")).connect(wallet);

  const BookLibrary = await hre.ethers.getContractFactory("BookLibrary"); // It will use the first of default wallets generated by Tenderly
  const bookLibrary = await BookLibrary.deploy();
  await bookLibrary.waitForDeployment();

  console.log("bookLibrary contract deployed: ", await bookLibrary.getAddress());
}

main().catch((error) => {
  console.error(error);
  process.exitCode = 1;
});