server:
  port: 8763
spring:
  application:
    name: authentication-service

eureka:
  instance:
    preferIpAddress: true
    hostname: localhost
  client:
    register-with-eureka: true
    fetch-registry: true
    serviceUrl:
      defaultZone: ${EUREKA_URI:http://localhost:8761/eureka}

management:
  endpoints:
    web:
      exposure:
        include: health, info

jannessa:
  app:
    jwtSecret: jannessaSecretKey
    jwtExpirationMs: 86400000