const {ethers} = require('ethers')

const contractAdd = '0x5FbDB2315678afecb367f032d93F642f64180aa3'  // assume this is the address you got from 03_deployContract.js
const abi = [
    'function setMsg(string _mesg) public',
    'function getMsg() public view returns(string)',
    'event logger(address indexed from, string indexed method, string mesg)'
]

function getWallet() {
    // 利用公共rpc节点连接以太坊网络
    // 可以在 https://chainlist.org 上找到
    //const SEPOLIA_URL = 'https://rpc.sepolia.org';
    //const providerSepolia = new ethers.JsonRpcProvider(SEPOLIA_URL)
    const provider = new ethers.JsonRpcProvider('http://127.0.0.1:8545/')
    const privateKey = '0xac0974bec39a17e36ba4a6b4d238ff944bacb478cbed5efcae784d7bf4f2ff80'
    const wallet = new ethers.Wallet(privateKey, provider)
    return wallet
}
function getProvider() {
    // 利用公共rpc节点连接以太坊网络
    // 可以在 https://chainlist.org 上找到
    //const SEPOLIA_URL = 'https://rpc.sepolia.org';
    //const providerSepolia = new ethers.JsonRpcProvider(SEPOLIA_URL)
    const provider = new ethers.JsonRpcProvider('http://127.0.0.1:8545/')
    return provider
}

async function decodeTx() {
    const provider = getProvider()
    // assume it is the a transaction hash id for the transaction generated by calling  setMsg in HelloWorld.sol 
    const txHash = '0x67c9d7af63abccfe947bfedb76df0b827a96037c50ec71e27700bd0d42ea1e0a'  
    const tx = await provider.getTransaction(txHash)
    console.log(tx)
    const iface = new ethers.Interface([
        'function setMsg(string _mesg) public'
    ])
    const selector = iface.getFunction('setMsg').selector
    console.log("selector:\n", selector)
    console.log(iface.parseTransaction(tx))
    console.log('message::', iface.parseTransaction(tx).args[0])
}

decodeTx()