import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <div className="w-1/2 mx-auto my-32 rounded-lg shadow-md border-2 border-zinc-400 p-5 bg-zinc-200">
          <div className="flex flex-col items-center mb-8 my-2">
            <div className="text-6xl font-semibold py-5">Welcome to voting!</div>
            {children}
          </div>
        </div>
      </body>
    </html>
  );
}
