server :
  port: 8080
  servlet:
    session:
      timeout: 3600

spring :
  datasource :
    url : jdbc:mysql://192.168.1.107:3306/sso_spring_session?useSSL=false&allowPublicKeyRetrieval=true
    username : demouser
    password : password
    driver-class-name : com.mysql.cj.jdbc.Driver


  session:
    store-type: redis
    redis:
      flush-mode: on_save
      namespace: spring:session

  redis:
    host: 192.168.1.107
    port: 6379
    password: password

  jpa :
    properties :
      hibernate :
        dialect :  org.hibernate.dialect.MySQLDialect
    hibernate :
      ddl-auto : none
      naming :
        physical-strategy : org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl

