spring:
  redis:
    host: 192.168.1.107
    port: 6379
    password: password
  session:
    store-type: redis    # @EnableRedisHttpSession
    redis:
      flush-mode: on_save
      namespace: spring:session
server:
  servlet:
    session:
      timeout: 3600

